server:
  port: 1111
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: WELCOME-SERVICE
  boot:
    admin:
      client:
        url: http://localhost:9090/